### ISSUE TITLE
Expressions always false

### ISSUE THREAD

**Issue by bartblaze** [malpedia/signator-rules#2]
FYI - 2 rules will not work due to the condition not being able to match:

```
warning: rule "win_samsam_auto" in may_malpedia_2024.yar(166090): expression always false - requesting 7 of 5.
warning: rule "win_zhmimikatz_auto" in may_malpedia_2024.yar(218544): expression always false - requesting 7 of 1.
```

**Comment by danielplohmann** [comment]
Hey Bart!

I'm a bit confused, as those rules are no longer in the repo, at least no files with that name and also no files containing either strings "samsam" or "zhmimikatz".

Is it possible that you have artifacts of older rules in there?

Otherwise, did you pull the rules from malpedia via the API - I just checked in the repo over there and there were rules matching your logical errors. Those are fixed now and should show up in a second. :)

Thanks for reporting back these issues in any case!!

**Comment by bartblaze** [comment]
Hi Daniel, I believe I may have done both at the time ;) Thnx for tackling it, and the great work!
